export const GRAPE_VARIETIES = [
  "Riesling",
  "Chardonnay",
  "Sauvignon Blanc",
  "Pinot Grigio",
  "Grauburgunder",
  "Weißburgunder",
  "Müller-Thurgau",
  "Silvaner",
  "Grüner Veltliner",
  "Chenin Blanc",
  "Viognier",
  "Gewürztraminer",
  "Muskateller",
  "Spätburgunder",
  "Pinot Noir",
  "Cabernet Sauvignon",
  "Merlot",
  "Syrah",
  "Shiraz",
  "Grenache",
  "Tempranillo",
  "Sangiovese",
  "Nebbiolo",
  "Malbec",
  "Zinfandel",
  "Primitivo",
  "Dornfelder",
  "Lemberger",
  "Blaufränkisch",
  "Cabernet Franc",
  "Petit Verdot",
  "Carmenere",
  "Gamay",
  "Barbera",
  "Montepulciano",
  "Nero d'Avola",
  "Garnacha",
  "Mourvèdre",
  "Petite Sirah",
  "Vermentino",
  "Albariño",
  "Godello",
  "Verdejo",
  "Trebbiano",
  "Cortese",
  "Garganega",
  "Furmint",
  "Assyrtiko"
].sort();

export const WINE_REGIONS = [
  "Bordeaux",
  "Burgund",
  "Champagne",
  "Rhône",
  "Loire",
  "Elsass",
  "Toskana",
  "Piemont",
  "Venetien",
  "Sizilien",
  "Apulien",
  "Rioja",
  "Ribera del Duero",
  "Priorat",
  "Pfalz",
  "Rheinhessen",
  "Mosel",
  "Rheingau",
  "Baden",
  "Franken",
  "Nahe",
  "Ahr",
  "Wachau",
  "Burgenland",
  "Steiermark",
  "Napa Valley",
  "Sonoma Coast",
  "Marlborough",
  "Stellenbosch",
  "Barossa Valley",
  "Mendoza",
  "Casablanca Valley",
  "Douro",
  "Alentejo",
  "Tokaj",
  "Santorini",
  "Chablis",
  "Sancerre",
  "Pauillac",
  "Saint-Émilion",
  "Margaux",
  "Barolo",
  "Barbaresco",
  "Brunello di Montalcino",
  "Chianti Classico",
  "Amarone della Valpolicella"
].sort();
